# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-19 04:22
from __future__ import unicode_literals

import app.mixins
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CronJob',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('status', models.CharField(max_length=50)),
            ],
            bases=(models.Model, app.mixins.HelperMixins),
        ),
        migrations.CreateModel(
            name='CronJob_Choices',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('cronjob_id', models.IntegerField()),
            ],
            bases=(models.Model, app.mixins.HelperMixins),
        ),
        migrations.CreateModel(
            name='CronJobType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
            bases=(models.Model, app.mixins.HelperMixins),
        ),
        migrations.CreateModel(
            name='CronJobType_Choices',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('cronjobtype_id', models.IntegerField()),
            ],
            bases=(models.Model, app.mixins.HelperMixins),
        ),
        migrations.CreateModel(
            name='GroupOwner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            bases=(models.Model, app.mixins.HelperMixins),
        ),
        migrations.CreateModel(
            name='GroupOwner_Choices',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('groupowner_id', models.IntegerField()),
            ],
            bases=(models.Model, app.mixins.HelperMixins),
        ),
        migrations.CreateModel(
            name='League',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('league_icon_path', models.CharField(max_length=250)),
                ('league_label_path', models.CharField(max_length=250)),
            ],
            options={
                'ordering': ['sport'],
            },
            bases=(models.Model, app.mixins.HelperMixins),
        ),
        migrations.CreateModel(
            name='League_Choices',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('league_id', models.IntegerField()),
            ],
            bases=(models.Model, app.mixins.HelperMixins),
        ),
        migrations.CreateModel(
            name='NFL_Conference',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('league', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.League')),
            ],
            options={
                'ordering': ['league'],
            },
            bases=(models.Model, app.mixins.HelperMixins),
        ),
        migrations.CreateModel(
            name='NFL_Conference_Choices',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('conference_id', models.IntegerField()),
            ],
            bases=(models.Model, app.mixins.HelperMixins),
        ),
        migrations.CreateModel(
            name='NFL_Division',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('conference', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.NFL_Conference')),
            ],
            options={
                'ordering': ['name'],
            },
            bases=(models.Model, app.mixins.HelperMixins),
        ),
        migrations.CreateModel(
            name='NFL_Division_Choices',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('division_id', models.IntegerField()),
            ],
            bases=(models.Model, app.mixins.HelperMixins),
        ),
        migrations.CreateModel(
            name='NFL_Schedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('is_custom', models.BooleanField(default=False)),
                ('cronjob', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='app.CronJob')),
            ],
            bases=(models.Model, app.mixins.HelperMixins),
        ),
        migrations.CreateModel(
            name='NFL_Season',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('league', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.League')),
            ],
            options={
                'ordering': ['-year'],
            },
            bases=(models.Model, app.mixins.HelperMixins),
        ),
        migrations.CreateModel(
            name='NFL_SeasonType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('league', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='app.League')),
            ],
            bases=(models.Model, app.mixins.HelperMixins),
        ),
        migrations.CreateModel(
            name='NFL_Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('location', models.CharField(max_length=50)),
                ('team_abbrv', models.CharField(max_length=10)),
                ('label_filename', models.CharField(max_length=50)),
                ('icon_filename', models.CharField(max_length=50)),
            ],
            options={
                'ordering': ['division'],
            },
            bases=(models.Model, app.mixins.HelperMixins),
        ),
        migrations.CreateModel(
            name='NFL_TeamCode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
            bases=(models.Model, app.mixins.HelperMixins),
        ),
        migrations.CreateModel(
            name='Pool',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('cronjob', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='app.CronJob')),
            ],
            bases=(models.Model, app.mixins.HelperMixins),
        ),
        migrations.CreateModel(
            name='PoolGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('groupowner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.GroupOwner')),
            ],
            options={
                'ordering': ['groupowner'],
            },
            bases=(models.Model, app.mixins.HelperMixins),
        ),
        migrations.CreateModel(
            name='PoolGroup_Choices',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('poolgroup_id', models.IntegerField()),
            ],
            bases=(models.Model, app.mixins.HelperMixins),
        ),
        migrations.CreateModel(
            name='PoolOwner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('poolgroup', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.PoolGroup')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['poolgroup'],
            },
            bases=(models.Model, app.mixins.HelperMixins),
        ),
        migrations.CreateModel(
            name='PoolOwner_Choices',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('poolowner_id', models.IntegerField()),
            ],
            bases=(models.Model, app.mixins.HelperMixins),
        ),
        migrations.CreateModel(
            name='PoolType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
            bases=(models.Model, app.mixins.HelperMixins),
        ),
        migrations.CreateModel(
            name='PoolType_Choices',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('pooltype_id', models.IntegerField()),
            ],
            bases=(models.Model, app.mixins.HelperMixins),
        ),
        migrations.CreateModel(
            name='Sport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
            bases=(models.Model, app.mixins.HelperMixins),
        ),
        migrations.CreateModel(
            name='Sport_Choices',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('sport_id', models.IntegerField()),
            ],
            bases=(models.Model, app.mixins.HelperMixins),
        ),
        migrations.CreateModel(
            name='SuperUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            bases=(models.Model, app.mixins.HelperMixins),
        ),
        migrations.CreateModel(
            name='Years',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
            ],
            bases=(models.Model, app.mixins.HelperMixins),
        ),
        migrations.AddField(
            model_name='pool',
            name='poolgroup',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.PoolGroup'),
        ),
        migrations.AddField(
            model_name='pool',
            name='poolowner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='app.PoolOwner'),
        ),
        migrations.AddField(
            model_name='pool',
            name='pooltype',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='app.PoolType'),
        ),
        migrations.AddField(
            model_name='nfl_team',
            name='code',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='app.NFL_TeamCode'),
        ),
        migrations.AddField(
            model_name='nfl_team',
            name='division',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.NFL_Division'),
        ),
        migrations.AddField(
            model_name='nfl_team',
            name='end_year',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='end_year', to='app.Years'),
        ),
        migrations.AddField(
            model_name='nfl_team',
            name='start_year',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='start_year', to='app.Years'),
        ),
        migrations.AddField(
            model_name='nfl_season',
            name='year',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='app.Years'),
        ),
        migrations.AddField(
            model_name='nfl_schedule',
            name='schedule_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='app.NFL_SeasonType'),
        ),
        migrations.AddField(
            model_name='nfl_schedule',
            name='season',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.NFL_Season'),
        ),
        migrations.AddField(
            model_name='league',
            name='sport',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Sport'),
        ),
        migrations.AddField(
            model_name='cronjob',
            name='cronjobtype',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.CronJobType'),
        ),
    ]
