# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-19 16:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_remove_nfl_schedule_cronjob'),
    ]

    operations = [
        migrations.AddField(
            model_name='cronjob',
            name='nfl_schedule',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='app.NFL_Schedule'),
        ),
        migrations.AddField(
            model_name='nfl_schedule',
            name='cronjob_id',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
