# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-29 02:25
from __future__ import unicode_literals

import app.mixins
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0004_auto_20161128_1804'),
    ]

    operations = [
        migrations.RenameField(
            model_name='poolowner_choices',
            old_name='poolowner',
            new_name='poolowner_id',
        ),
    ]
