# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-19 16:49
from __future__ import unicode_literals

import app.mixins
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20161219_0930'),
    ]

    operations = [
        migrations.CreateModel(
            name='NFL_TimePeriod',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
            ],
            options={
                'ordering': ['schedule'],
            },
            bases=(models.Model, app.mixins.HelperMixins),
        ),
        migrations.AlterModelOptions(
            name='nfl_schedule',
            options={'ordering': ['-season']},
        ),
        migrations.AddField(
            model_name='nfl_timeperiod',
            name='schedule',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.NFL_Schedule'),
        ),
    ]
