# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-19 17:59
from __future__ import unicode_literals

import app.mixins
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_auto_20161219_0949'),
    ]

    operations = [
        migrations.CreateModel(
            name='NFL_Game',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nfl_gamekey', models.CharField(max_length=15)),
                ('nfl_eid', models.CharField(max_length=15)),
                ('nfl_wknum', models.IntegerField()),
                ('nfl_seasontype', models.CharField(max_length=10)),
                ('nfl_hometeam_abbrv', models.CharField(max_length=10)),
                ('nfl_awayteam_abbrv', models.CharField(max_length=10)),
                ('nfl_merdian', models.CharField(max_length=10)),
                ('nfl_year', models.IntegerField()),
                ('nfl_month', models.IntegerField()),
                ('nfl_day', models.IntegerField()),
                ('nfl_wkday', models.CharField(max_length=10)),
                ('nfl_time', models.CharField(max_length=10)),
                ('start_time', models.DateTimeField()),
                ('data_error', models.CharField(max_length=10, null=True)),
                ('nfl_awayteam', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='nfl_awayteam', to='app.NFL_Team')),
                ('nfl_hometeam', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='nfl_hometeam', to='app.NFL_Team')),
                ('timeperiod', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='app.NFL_TimePeriod')),
            ],
            options={
                'ordering': ['nfl_gamekey'],
            },
            bases=(models.Model, app.mixins.HelperMixins),
        ),
    ]
