# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-19 18:47
from __future__ import unicode_literals

import app.mixins
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_nfl_game'),
    ]

    operations = [
        migrations.CreateModel(
            name='NFL_Game_Choices',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('nfl_game_id', models.IntegerField()),
            ],
            bases=(models.Model, app.mixins.HelperMixins),
        ),
        migrations.CreateModel(
            name='NFL_Schedule_Choices',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('nfl_schedule_id', models.IntegerField()),
            ],
            bases=(models.Model, app.mixins.HelperMixins),
        ),
        migrations.CreateModel(
            name='NFL_Season_Choices',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('nfl_season_id', models.IntegerField()),
            ],
            bases=(models.Model, app.mixins.HelperMixins),
        ),
        migrations.CreateModel(
            name='NFL_SeasonType_Choices',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('nfl_seasontype_id', models.IntegerField()),
            ],
            bases=(models.Model, app.mixins.HelperMixins),
        ),
        migrations.CreateModel(
            name='NFL_Team_Choices',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('nfl_team_id', models.IntegerField()),
            ],
            bases=(models.Model, app.mixins.HelperMixins),
        ),
        migrations.CreateModel(
            name='NFL_TimePeriod_Choices',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('nfl_timeperiod_id', models.IntegerField()),
            ],
            bases=(models.Model, app.mixins.HelperMixins),
        ),
        migrations.CreateModel(
            name='Pool_Choices',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('pool_id', models.IntegerField()),
            ],
            bases=(models.Model, app.mixins.HelperMixins),
        ),
        migrations.CreateModel(
            name='Years_Choices',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('years_id', models.IntegerField()),
            ],
            bases=(models.Model, app.mixins.HelperMixins),
        ),
    ]
